name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Generate graph (if applicable)
      run: |
        python generate_graph.py  # Si ton script est celui qui génère le graphe, remplace par ton script réel

    - name: Upload graph artifact
      uses: actions/upload-artifact@v3
      with:
        name: graph
        path: path/to/graph.png  # Remplace par le chemin réel de ton fichier généré
